name: Test

on:
  - push
  - workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: '11'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: gradle.wrapper-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: gradle.wrapper-

      - name: Cache Gradle Caches
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: gradle.caches-${{ hashFiles('**/*.gradle') }}
          restore-keys: gradle.caches-

      - name: Run Tests
        run: ./gradlew test
        env: 
          RUN_ON_GITHUB_ACTIONS: "yes"

      - name: report
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with: 
          name: http-spec-test-reports
          if-no-files-found: warn
          path: build/reports
